// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZAd0CQsJpN1WqHKLUjBLSmDux7wlnU2I',
    appId: '1:442296758907:web:61d3cb5476f7075bef28de',
    messagingSenderId: '442296758907',
    projectId: 'hossam-por',
    authDomain: 'hossam-por.firebaseapp.com',
    storageBucket: 'hossam-por.firebasestorage.app',
    measurementId: 'G-RJVCG9CKVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3z0Zktf-7SqqAbELBJ9sb9IDJsir7yME',
    appId: '1:442296758907:android:48ab8781ff63a96cef28de',
    messagingSenderId: '442296758907',
    projectId: 'hossam-por',
    storageBucket: 'hossam-por.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUB7kTVegP0CM4ofOcEK9fBW0P8lupKBU',
    appId: '1:442296758907:ios:e8e10d7daa8cb123ef28de',
    messagingSenderId: '442296758907',
    projectId: 'hossam-por',
    storageBucket: 'hossam-por.firebasestorage.app',
    iosBundleId: 'com.example.hossamPr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUB7kTVegP0CM4ofOcEK9fBW0P8lupKBU',
    appId: '1:442296758907:ios:e8e10d7daa8cb123ef28de',
    messagingSenderId: '442296758907',
    projectId: 'hossam-por',
    storageBucket: 'hossam-por.firebasestorage.app',
    iosBundleId: 'com.example.hossamPr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZAd0CQsJpN1WqHKLUjBLSmDux7wlnU2I',
    appId: '1:442296758907:web:7ccaf6fe4982d76cef28de',
    messagingSenderId: '442296758907',
    projectId: 'hossam-por',
    authDomain: 'hossam-por.firebaseapp.com',
    storageBucket: 'hossam-por.firebasestorage.app',
    measurementId: 'G-5XNLVE4V1K',
  );
}
